---
# Installation
- name: Add sid apt repository
  apt_repository: repo='deb http://ftp.debian.org/debian/ sid main' state=present
  when: ansible_distribution == 'Debian' and
        ansible_distribution_release == 'jessie'

- name: Install aMule
  apt: name=amule-daemon state=present
  when: ansible_distribution_release != 'jessie'

- name: Install aMule
  apt: name=amule-daemon state=present update_cache=yes default_release=sid
  when: ansible_distribution == 'Debian' and
        ansible_distribution_release == 'jessie'

- name: Remove sid apt repository
  apt_repository: repo='deb http://ftp.debian.org/debian/ sid main' state=absent
  when: ansible_distribution == 'Debian' and
        ansible_distribution_release == 'jessie'

- name: Update apt cache
  apt: update_cache=yes
  when: ansible_distribution == 'Debian' and
        ansible_distribution_release == 'jessie'

# Configuration
- name: Make sure aMule is not running
  service: name=amule-daemon state=stopped
  ignore_errors: true

- name: Set aMule daemon user
  replace:
    dest=/etc/default/amule-daemon
    regexp='AMULED_USER=""'
    replace='AMULED_USER="{{ ansible_user_id }}"'

- name: Add incoming folder
  file:
    path={{ amule_incoming_dir }}
    owner={{ ansible_user_id }}
    group={{ ansible_user_id }}
    state=directory

- name: Add aMule config dir
  file:
    path={{ ansible_env.HOME }}/.aMule
    owner={{ ansible_user_id }}
    group={{ ansible_user_id }}
    state=directory

- name: Add temp folder
  file:
    path={{ amule_temp_dir }}
    owner={{ ansible_user_id }}
    group={{ ansible_user_id }}
    state=directory

- name: Copy aMule configuration
  template:
    src=amule.conf
    dest={{ ansible_env.HOME }}/.aMule/amule.conf
    owner={{ ansible_user_id }}
    group={{ ansible_user_id }}

# Service start
- name: Start aMule
  service: name=amule-daemon state=started
  ignore_errors: true
