---
# Installation
- name: Add sid apt repository
  apt_repository:
    repo: deb http://ftp.debian.org/debian/ sid main
    state: present
  when: ansible_distribution == 'Debian' and
        ansible_distribution_release == 'jessie'
  tags: amule

- name: Install aMule
  apt: name=amule-daemon state=present
  when: ansible_distribution_release != 'jessie'

- name: Install aMule
  apt:
    name: amule-daemon
    state: present
    update_cache: yes
    default_release: sid
  when: ansible_distribution == 'Debian' and
        ansible_distribution_release == 'jessie'
  tags: amule

- name: Remove sid apt repository
  apt_repository:
    repo: deb http://ftp.debian.org/debian/ sid main
    state: absent
  when: ansible_distribution == 'Debian' and
        ansible_distribution_release == 'jessie'
  tags: amule

- name: Update apt cache
  apt: update_cache=yes
  when: ansible_distribution == 'Debian' and
        ansible_distribution_release == 'jessie'
  tags: amule

# Configuration
- name: Make sure aMule is not running
  service: name=amule-daemon state=stopped
  ignore_errors: true
  tags: amule

- name: Set aMule daemon user
  replace:
    dest: /etc/default/amule-daemon
    regexp: 'AMULED_USER=""'
    replace: 'AMULED_USER="{{ ansible_user_id }}"'
  tags: amule

- name: Add incoming folder
  file:
    path: "{{ amule_incoming_dir }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory
  tags: amule

- name: Add aMule config dir
  file:
    path: "{{ ansible_env.HOME }}/.aMule"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory
  tags: amule

- name: Add temp folder
  file:
    path: "{{ amule_temp_dir }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory
  tags: amule

- name: Copy aMule configuration
  template:
    src: amule.conf
    dest: "{{ ansible_env.HOME }}/.aMule/amule.conf"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  notify: start amule
  tags: amule
